describe('deposit-crypto spec', () => {
    it('success deposit', () => {
        cy.visit('https://primecodex.com/')
        cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
        cy.get('#email').type("zkldn30@gmail.com")
        cy.get('#password').type("Acinanna3072")
        cy.get('.btn').click()
        cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
        cy.get('[href="/deposit-crypto"]').click()
        cy.get('#amount').type('2')
        cy.get('#nomor-akun').type('Bitcoin')
        cy.get('#term').click()
        cy.get('.btn').click()
    })

    it('success crypto address', () => {
        cy.visit('https://primecodex.com/')
        cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
        cy.get('#email').type("zkldn30@gmail.com")
        cy.get('#password').type("Acinanna3072")
        cy.get('.btn').click()
        cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
        cy.get('[href="/deposit-crypto"]').click()
        cy.get('#amount').type('2')
        cy.get('#term').click()
        cy.get('.btn').click()
    })

    it('Filling nothing out', () => {
        cy.visit('https://primecodex.com/')
        cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
        cy.get('#email').type("zkldn30@gmail.com")
        cy.get('#password').type("Acinanna3072")
        cy.get('.btn').click()
        cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
        cy.get('[href="/deposit-crypto"]').click()
        cy.get('#term').click()
        cy.get('.btn').click()
    })
})