describe('deposit-local spec', () => {
    it('success deposit', () => {
      cy.visit('https://primecodex.com/')
      cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
      cy.get('#email').type("zkldn30@gmail.com")
      cy.get('#password').type("Acinanna3072")
      cy.get('.btn').click()
      cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
      cy.get('#amount').type("2")
      cy.get('.bg_secondary > :nth-child(2) > input').type("John Bie")
      cy.get('#nomor-akun').type("123123123")
      cy.get('.ui').type("bank bni")
      cy.get('.item').contains('BANK BNI').click()
      cy.get('#term').click()
      cy.get('.btn').click()
    })

    it('empty amount', () => {
        cy.visit('https://primecodex.com/')
        cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
        cy.get('#email').type("zkldn30@gmail.com")
        cy.get('#password').type("Acinanna3072")
        cy.get('.btn').click()
        cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
        cy.get('.bg_secondary > :nth-child(2) > input').type("John Bie")
        cy.get('#nomor-akun').type("123123123")
        cy.get('.ui').type("bank bni")
        cy.get('.item').contains('BANK BNI').click()
        cy.get('#term').click()
        cy.get('.btn').click()
      })
    
    it('empty bank account name', () => {
      cy.visit('https://primecodex.com/')
      cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
      cy.get('#email').type("zkldn30@gmail.com")
      cy.get('#password').type("Acinanna3072")
      cy.get('.btn').click()
      cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
      cy.get('#amount').type("2")
      cy.get('#nomor-akun').type("123123123")
      cy.get('.ui').type("bank bni")
      cy.get('.item').contains('BANK BNI').click()
      cy.get('#term').click()
      cy.get('.btn').click()
    })

    it('empty bank account number', () => {
        cy.visit('https://primecodex.com/')
        cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
        cy.get('#email').type("zkldn30@gmail.com")
        cy.get('#password').type("Acinanna3072")
        cy.get('.btn').click()
        cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
        cy.get('#amount').type("2")
        cy.get('.bg_secondary > :nth-child(2) > input').type("John Bie")
        cy.get('.ui').type("bank bni")
        cy.get('.item').contains('BANK BNI').click()
        cy.get('#term').click()
        cy.get('.btn').click()
      })
})