describe('deposit-credit card spec', () => {
    it('success deposit', () => {
        cy.visit('https://primecodex.com/')
        cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
        cy.get('#email').type("zkldn30@gmail.com")
        cy.get('#password').type("Acinanna3072")
        cy.get('.btn').click()
        cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
        cy.get('.nav-depo > div > a').click()
        cy.get('#amount').type("2")
        cy.get('.bg_secondary > :nth-child(2) > input').type("John Bie")
        cy.get('#term').click()
        cy.get('.btn').click()
    })

    it('empty amount', () => {
        cy.visit('https://primecodex.com/')
        cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
        cy.get('#email').type("zkldn30@gmail.com")
        cy.get('#password').type("Acinanna3072")
        cy.get('.btn').click()
        cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
        cy.get('.nav-depo > div > a').click()
        cy.get('.bg_secondary > :nth-child(2) > input').type("John Bie")
        cy.get('#term').click()
        cy.get('.btn').click()
    })

    it('empty account name', () => {
        cy.visit('https://primecodex.com/')
        cy.get('[href="https://secure.primecodex.com/"] > .w-32').click()
        cy.get('#email').type("zkldn30@gmail.com")
        cy.get('#password').type("Acinanna3072")
        cy.get('.btn').click()
        cy.get('.sidebar-container > .menu-list > :nth-child(5) > .menu').click()
        cy.get('.nav-depo > div > a').click()
        cy.get('#amount').type("2")
        cy.get('#term').click()
        cy.get('.btn').click()
    })
})