describe('register spec', () => {
  it('success register', () => {
    cy.visit('https://primecodex.com/')
    cy.get('[href="/register/"] > .w-32').click()
    cy.get('#form-id-fullName').type('Mona Lisa')
    cy.get('#1').type('zkldn30@gmail.com')
    cy.get('.arrow').click()
    cy.get('.search-box').type("indonesia")
    cy.get('.country').contains('Indonesia').click()
    cy.get('.m-0 > .form-control').type("088888888888")
    cy.get('#4 ').type("Acinanna3072")
    cy.get('#5 ').type("Acinanna3072")
    cy.get('.w-48').click()
    cy.get('#form-id-country').type("Indonesia")
    cy.get('#1').type("Indonesia")
    cy.get('#2 ').type("Makassar")
    cy.get('#4 ').type("Perintis Kemerdekaan")
    cy.get('.w-6').click()
    cy.get('.w-48').click()
    cy.get(':nth-child(3) > form > .justify-start > .w-6').click()
    cy.get('.border-1 > .w-6').click()
    cy.contains('Open Account').click();
  })

  it('empty fullname', () => {
    cy.visit('https://primecodex.com/')
    cy.get('[href="/register/"] > .w-32').click()
    cy.get('#1').type('zkldn30@gmail.com')
    cy.get('.arrow').click()
    cy.get('.search-box').type("indonesia")
    cy.get('.country').contains('Indonesia').click()
    cy.get('.m-0 > .form-control').type("088888888888")
    cy.get('#4 ').type("Acinanna3072")
    cy.get('#5 ').type("Acinanna3072")
    cy.get('.w-48').click()
    cy.get('#swal2-title').should('contain.text','OOPS!')
  })

  it('empty phone number', () => {
    cy.visit('https://primecodex.com/')
    cy.get('[href="/register/"] > .w-32').click()
    cy.get('#form-id-fullName').type('Mona Lisa')
    cy.get('#1').type('zkldn30@gmail.com')
    cy.get('.arrow').click()
    cy.get('.search-box').type("indonesia")
    cy.get('.country').contains('Indonesia').click()
    cy.get('#4 ').type("Acinanna3072")
    cy.get('#5 ').type("Acinanna3072")
    cy.get('.w-48').click()
    cy.get('#form-id-country').type("Indonesia")
    cy.get('#1').type("Indonesia")
    cy.get('#2 ').type("Makassar")
    cy.get('#4 ').type("Perintis Kemerdekaan")
    cy.get('.w-6').click()
    cy.get('.w-48').click()
    cy.get(':nth-child(3) > form > .justify-start > .w-6').click()
    cy.get('.border-1 > .w-6').click()
    cy.contains('Open Account').click();
  })

  it('empty email', () => {
    cy.visit('https://primecodex.com/')
    cy.get('[href="/register/"] > .w-32').click()
    cy.get('#form-id-fullName').type('Mona Lisa')
    cy.get('.arrow').click()
    cy.get('.search-box').type("indonesia")
    cy.get('.country').contains('Indonesia').click()
    cy.get('.m-0 > .form-control').type("088888888888")
    cy.get('#4 ').type("Acinanna3072")
    cy.get('#5 ').type("Acinanna3072")
    cy.get('.w-48').click()
    cy.get('#swal2-title').should('contain.text','OOPS!')
  })
})